import type { Product } from "@/lib/types";

/**
 * PLACEHOLDER INVENTORY (brief §8, Pending #2).
 * Realistic, well-known Mauritius experiences so the site is fully demonstrable.
 * Every item is `draft: true` and every price is a flagged PLACEHOLDER awaiting the
 * client's real list, durations, inclusions and pricing. Never presented as final.
 * Starting prices only ("From €XX") — never full price tables (brief §13).
 */

const PRICE_NOTE = "PLACEHOLDER — awaiting client pricing";

export const products: Product[] = [
  {
    slug: "south-island-discovery",
    productType: "tour",
    title: "South Island Discovery",
    hook: "Coloured earths, sacred lake and waterfalls in one unforgettable day.",
    summary:
      "The classic south circuit: the surreal Seven Coloured Earths at Chamarel, the sacred lake of Grand Bassin, dramatic waterfalls and sweeping viewpoints over the Black River gorges — with a local guide to bring each stop to life.",
    region: "South",
    duration: "Full day · about 8 hours",
    fromPrice: 95,
    currency: "EUR",
    priceNote: PRICE_NOTE,
    groupType: "Private",
    highlights: [
      "Seven Coloured Earths & Chamarel Waterfall",
      "Grand Bassin (Ganga Talao) sacred lake",
      "Black River Gorges viewpoint",
      "Rhumerie de Chamarel (optional tasting)",
      "Panoramic south-coast photo stops",
    ],
    included: [
      "Private air-conditioned vehicle",
      "Experienced English-speaking driver-guide",
      "Hotel pickup and drop-off",
      "Bottled water",
      "All road tolls and parking",
    ],
    excluded: [
      "Entrance fees (Seven Coloured Earths, gardens)",
      "Lunch and drinks",
      "Optional activities and tastings",
      "Gratuities",
    ],
    itinerary: [
      { title: "Hotel pickup", description: "Morning collection from your hotel or preferred location." },
      { title: "Grand Bassin", description: "Visit the island's most important Hindu pilgrimage site around a volcanic crater lake." },
      { title: "Black River Gorges viewpoint", description: "Sweeping views over Mauritius's largest national park and its endemic forest." },
      { title: "Chamarel", description: "The Seven Coloured Earths dunes and the Chamarel Waterfall, with time for photos." },
      { title: "South-west coast", description: "Scenic coastal stops before returning to your hotel in the late afternoon." },
    ],
    tags: ["Nature", "Culture", "Scenery", "Family-friendly"],
    mapArea: { label: "South-west Mauritius — Chamarel & Grand Bassin", query: "Seven Coloured Earths, Chamarel, Mauritius" },
    hero: { id: "south-chamarel-hero", alt: "Aerial view of the Seven Coloured Earths dunes at Chamarel, southern Mauritius", tone: "sunset", orientation: "wide" },
    gallery: [
      { id: "south-grand-bassin", alt: "Sacred lake of Grand Bassin with temple statues, Mauritius", tone: "forest", orientation: "landscape" },
      { id: "south-chamarel-falls", alt: "Chamarel Waterfall plunging into forested gorge", tone: "forest", orientation: "portrait" },
      { id: "south-black-river-view", alt: "Panorama over Black River Gorges National Park", tone: "forest", orientation: "landscape" },
    ],
    featured: true,
    draft: true,
  },
  {
    slug: "north-cap-malheureux",
    productType: "tour",
    title: "North Island & Cap Malheureux",
    hook: "Red-roof church, botanical wonders and the buzz of Grand Baie.",
    summary:
      "Explore the vibrant north: the iconic red-roofed church at Cap Malheureux facing the northern islets, the historic Pamplemousses Botanical Garden with its giant water lilies, and the lively seaside village of Grand Baie.",
    region: "North",
    duration: "Full day · about 8 hours",
    fromPrice: 89,
    currency: "EUR",
    priceNote: PRICE_NOTE,
    groupType: "Private",
    highlights: [
      "Cap Malheureux red-roofed church & islet views",
      "Sir Seewoosagur Ramgoolam Botanical Garden",
      "Grand Baie village and seafront",
      "Northern coastal viewpoints",
      "Optional Port Louis add-on",
    ],
    included: [
      "Private air-conditioned vehicle",
      "Experienced English-speaking driver-guide",
      "Hotel pickup and drop-off",
      "Bottled water",
      "All road tolls and parking",
    ],
    excluded: [
      "Botanical garden entrance fee",
      "Lunch and drinks",
      "Optional boat trips",
      "Gratuities",
    ],
    itinerary: [
      { title: "Hotel pickup", description: "Morning collection from your hotel or preferred location." },
      { title: "Pamplemousses Garden", description: "Wander one of the oldest botanical gardens in the southern hemisphere." },
      { title: "Cap Malheureux", description: "Photograph the famous red-roofed chapel with the northern islets behind it." },
      { title: "Grand Baie", description: "Free time in the north's most popular village for lunch and the seafront." },
      { title: "Return", description: "Afternoon return to your hotel." },
    ],
    tags: ["Culture", "Gardens", "Coast", "Family-friendly"],
    mapArea: { label: "Northern Mauritius — Cap Malheureux & Grand Baie", query: "Cap Malheureux, Mauritius" },
    hero: { id: "north-cap-malheureux-hero", alt: "Red-roofed church at Cap Malheureux with turquoise sea and northern islets", tone: "ocean", orientation: "wide" },
    gallery: [
      { id: "north-pamplemousses", alt: "Giant Victoria water lilies at Pamplemousses Botanical Garden", tone: "forest", orientation: "landscape" },
      { id: "north-grand-baie", alt: "Boats moored in the turquoise bay at Grand Baie", tone: "lagoon", orientation: "landscape" },
      { id: "north-coast", alt: "Northern coastline of Mauritius at golden hour", tone: "sunset", orientation: "portrait" },
    ],
    featured: true,
    draft: true,
  },
  {
    slug: "ile-aux-cerfs-catamaran",
    productType: "tour",
    title: "Île aux Cerfs Catamaran Day",
    hook: "Sail the east-coast lagoon to a postcard island paradise.",
    summary:
      "A full day on the water: cruise the sheltered east-coast lagoon by catamaran, snorkel over coral, visit the GRSE waterfall from the sea, and relax on the powder-white beaches of Île aux Cerfs with a barbecue lunch on board.",
    region: "East",
    duration: "Full day · about 8 hours",
    fromPrice: 110,
    currency: "EUR",
    priceNote: PRICE_NOTE,
    groupType: "Small group",
    highlights: [
      "Catamaran cruise on the east lagoon",
      "Snorkelling over coral gardens",
      "Grand River South East waterfall from the water",
      "Beach time on Île aux Cerfs",
      "Barbecue lunch on board",
    ],
    included: [
      "Return hotel transfers",
      "Catamaran cruise with crew",
      "Snorkelling equipment",
      "Barbecue lunch and soft drinks",
      "Bottled water",
    ],
    excluded: [
      "Water sports on the island",
      "Alcoholic drinks",
      "Gratuities",
      "Personal expenses",
    ],
    itinerary: [
      { title: "Hotel pickup", description: "Transfer to the east-coast departure point." },
      { title: "Set sail", description: "Board the catamaran and cruise into the lagoon." },
      { title: "Snorkel stop", description: "Anchor over coral for snorkelling and swimming." },
      { title: "GRSE waterfall", description: "Approach the Grand River South East waterfall by boat." },
      { title: "Île aux Cerfs", description: "Beach time and barbecue lunch on the island." },
      { title: "Return cruise", description: "Sail back mid-afternoon and transfer to your hotel." },
    ],
    tags: ["Beach", "Snorkelling", "Boat", "Family-friendly"],
    mapArea: { label: "East coast — Île aux Cerfs lagoon", query: "Ile aux Cerfs, Mauritius" },
    hero: { id: "ile-aux-cerfs-hero", alt: "Catamaran anchored over turquoise lagoon near Île aux Cerfs, east Mauritius", tone: "lagoon", orientation: "wide" },
    gallery: [
      { id: "cerfs-beach", alt: "White-sand beach and casuarina trees on Île aux Cerfs", tone: "lagoon", orientation: "landscape" },
      { id: "cerfs-snorkel", alt: "Snorkeller above a coral garden in clear water", tone: "ocean", orientation: "portrait" },
      { id: "cerfs-grse-waterfall", alt: "Grand River South East waterfall meeting the sea", tone: "forest", orientation: "landscape" },
    ],
    featured: true,
    draft: true,
  },
  {
    slug: "port-louis-cultural-market",
    productType: "tour",
    title: "Port Louis Cultural & Market Tour",
    hook: "The capital's markets, monuments and multicultural streets.",
    summary:
      "A half-day through the heart of the capital: the bustling Central Market, the UNESCO-listed Aapravasi Ghat, the Caudan waterfront, and viewpoints from Fort Adelaide over the city and harbour — a vivid introduction to Mauritius's cultural mix.",
    region: "Central",
    duration: "Half day · about 4 hours",
    fromPrice: 65,
    currency: "EUR",
    priceNote: PRICE_NOTE,
    groupType: "Private",
    highlights: [
      "Port Louis Central Market",
      "Aapravasi Ghat (UNESCO World Heritage)",
      "Caudan Waterfront",
      "Fort Adelaide (Citadel) viewpoint",
      "Champ de Mars racecourse",
    ],
    included: [
      "Private air-conditioned vehicle",
      "Experienced English-speaking driver-guide",
      "Hotel pickup and drop-off",
      "Bottled water",
      "All road tolls and parking",
    ],
    excluded: [
      "Museum entrance fees",
      "Lunch and drinks",
      "Shopping and personal expenses",
      "Gratuities",
    ],
    itinerary: [
      { title: "Hotel pickup", description: "Morning collection and drive to the capital." },
      { title: "Central Market", description: "Explore stalls of spices, fruit, crafts and street food." },
      { title: "Aapravasi Ghat", description: "Visit the historic immigration depot, a UNESCO World Heritage Site." },
      { title: "Fort Adelaide", description: "Panoramic views over Port Louis and the harbour." },
      { title: "Caudan Waterfront", description: "Free time along the redeveloped harbourfront before returning." },
    ],
    tags: ["Culture", "History", "City", "Food"],
    mapArea: { label: "Port Louis — the capital", query: "Central Market, Port Louis, Mauritius" },
    hero: { id: "port-louis-hero", alt: "Port Louis harbour and Caudan Waterfront with mountains behind", tone: "ocean", orientation: "wide" },
    gallery: [
      { id: "pl-market", alt: "Colourful spice and produce stalls in Port Louis Central Market", tone: "sunset", orientation: "portrait" },
      { id: "pl-aapravasi", alt: "Stone steps of the Aapravasi Ghat World Heritage Site", tone: "sand", orientation: "landscape" },
      { id: "pl-citadel", alt: "View over Port Louis rooftops from Fort Adelaide", tone: "ocean", orientation: "landscape" },
    ],
    draft: true,
  },
  {
    slug: "black-river-gorges-hiking",
    productType: "tour",
    title: "Black River Gorges Nature & Hiking",
    hook: "Endemic forest, waterfalls and viewpoints on foot.",
    summary:
      "For nature lovers: guided walking trails in Black River Gorges National Park, home to Mauritius's last native forest and rare endemic birds, with stops at Alexandra Falls and the Gorges viewpoint and time among giant ebony and tambalacoque trees.",
    region: "West",
    duration: "Full day · about 7 hours",
    fromPrice: 79,
    currency: "EUR",
    priceNote: PRICE_NOTE,
    groupType: "Small group",
    highlights: [
      "Guided trail in the last native forest",
      "Alexandra Falls viewpoint",
      "Gorges viewpoint panorama",
      "Endemic birds and plants",
      "Petrin heathland",
    ],
    included: [
      "Private air-conditioned vehicle",
      "Experienced nature driver-guide",
      "Hotel pickup and drop-off",
      "Bottled water",
      "Guided walk",
    ],
    excluded: [
      "Lunch and drinks",
      "Hiking shoes and personal gear",
      "Gratuities",
      "Travel insurance",
    ],
    itinerary: [
      { title: "Hotel pickup", description: "Early collection to make the most of the cool morning." },
      { title: "Petrin entrance", description: "Enter the national park at the upland heath." },
      { title: "Guided walk", description: "Walk a scenic trail with your guide explaining the endemic ecosystem." },
      { title: "Alexandra Falls", description: "Viewpoint over the falls and the southern plains." },
      { title: "Gorges viewpoint", description: "The park's signature panorama before the return drive." },
    ],
    tags: ["Nature", "Hiking", "Birdwatching", "Active"],
    mapArea: { label: "Black River Gorges National Park", query: "Black River Gorges Viewpoint, Mauritius" },
    hero: { id: "black-river-hero", alt: "Misty view over the forested valleys of Black River Gorges National Park", tone: "forest", orientation: "wide" },
    gallery: [
      { id: "brg-alexandra-falls", alt: "Alexandra Falls cascading into deep green forest", tone: "forest", orientation: "portrait" },
      { id: "brg-trail", alt: "Walking trail through native ebony forest", tone: "forest", orientation: "landscape" },
      { id: "brg-bird", alt: "Endemic Mauritius kestrel perched on a branch", tone: "forest", orientation: "square" },
    ],
    draft: true,
  },
  {
    slug: "full-island-private-day",
    productType: "tour",
    title: "Full-Island Private Day Tour",
    hook: "Your Mauritius, your way — a private day built around you.",
    summary:
      "A completely bespoke private day: tell us what you want to see — beaches, culture, nature, food, shopping — and we design the route around your interests, with a private vehicle and driver-guide for the whole day.",
    region: "Island-wide",
    duration: "Full day · up to 9 hours",
    fromPrice: 129,
    currency: "EUR",
    priceNote: PRICE_NOTE,
    groupType: "Private",
    highlights: [
      "Fully personalised itinerary",
      "Choose your regions and stops",
      "Flexible pace, private vehicle",
      "Local food and hidden-gem recommendations",
      "Ideal for first-time visitors",
    ],
    included: [
      "Private air-conditioned vehicle for the day",
      "Dedicated English-speaking driver-guide",
      "Hotel pickup and drop-off",
      "Bottled water",
      "All road tolls and parking",
    ],
    excluded: [
      "Entrance fees and activities",
      "Lunch and drinks",
      "Gratuities",
      "Personal expenses",
    ],
    itinerary: [
      { title: "Plan together", description: "We agree your priorities and route in advance over WhatsApp or email." },
      { title: "Hotel pickup", description: "Flexible morning start from your hotel." },
      { title: "Your stops", description: "Visit the places you chose, at your own pace." },
      { title: "Lunch", description: "A recommended local spot, or somewhere you have in mind." },
      { title: "Return", description: "Back to your hotel whenever suits you." },
    ],
    tags: ["Private", "Custom", "Flexible", "First visit"],
    mapArea: { label: "Anywhere in Mauritius", query: "Mauritius" },
    hero: { id: "full-island-hero", alt: "Coastal road winding along the Mauritius shoreline with mountains inland", tone: "ocean", orientation: "wide" },
    gallery: [
      { id: "island-beach", alt: "Empty white-sand beach with turquoise lagoon", tone: "lagoon", orientation: "landscape" },
      { id: "island-mountain", alt: "Le Morne Brabant mountain rising above the lagoon", tone: "ocean", orientation: "portrait" },
      { id: "island-food", alt: "Mauritian street food and tropical fruit", tone: "sunset", orientation: "square" },
    ],
    draft: true,
  },
  {
    slug: "five-day-mauritius-package",
    productType: "package",
    title: "Five-Day Mauritius Package",
    hook: "A complete five-day holiday, organised end to end.",
    summary:
      "Our signature five-day package brings together accommodation, airport transfers, guided tours, activities and full travel support — a complete Mauritius holiday planned by one team, then tailored to your interests and budget.",
    region: "Island-wide",
    duration: "5 days · 4 nights",
    fromPrice: 549,
    currency: "EUR",
    priceNote: PRICE_NOTE + " (per person, indicative)",
    groupType: "Private",
    highlights: [
      "Accommodation for four nights",
      "Airport transfers included",
      "Two guided tours (north and south)",
      "A lagoon catamaran day",
      "Full travel support throughout",
    ],
    included: [
      "4 nights' accommodation (to your budget)",
      "Return airport transfers",
      "Selected guided tours and activities",
      "Dedicated trip coordinator",
      "24/7 WhatsApp support during your stay",
    ],
    excluded: [
      "International flights (we can arrange these)",
      "Meals not specified",
      "Optional activities",
      "Travel insurance and personal expenses",
    ],
    itinerary: [
      { title: "Day 1 — Arrival", description: "Airport meet & greet, transfer and check-in." },
      { title: "Day 2 — The North", description: "Guided north-island tour and Grand Baie." },
      { title: "Day 3 — Lagoon day", description: "Catamaran cruise and beach time on the east coast." },
      { title: "Day 4 — The South", description: "Chamarel, Grand Bassin and the south circuit." },
      { title: "Day 5 — Departure", description: "Free morning, then transfer to the airport." },
    ],
    tags: ["Package", "All-in-one", "Best value", "Custom"],
    mapArea: { label: "Across Mauritius", query: "Mauritius" },
    hero: { id: "package-hero", alt: "Resort infinity pool overlooking a Mauritius lagoon at sunset", tone: "sunset", orientation: "wide" },
    gallery: [
      { id: "package-resort", alt: "Beachfront resort and palm trees on the Mauritius coast", tone: "lagoon", orientation: "landscape" },
      { id: "package-tour", alt: "Guide and travellers at a scenic Mauritius viewpoint", tone: "forest", orientation: "landscape" },
      { id: "package-catamaran", alt: "Catamaran sailing on a calm turquoise lagoon", tone: "lagoon", orientation: "portrait" },
    ],
    draft: true,
  },
  {
    slug: "airport-transfer-private",
    productType: "transfer",
    title: "Private Airport Transfer",
    hook: "A driver waiting when you land — anywhere on the island.",
    summary:
      "Private airport transfers between Sir Seewoosagur Ramgoolam International Airport and your hotel or any location in Mauritius. Meet & greet on arrival, fixed transparent pricing, and clean, comfortable, air-conditioned vehicles.",
    region: "Island-wide",
    duration: "One way or return",
    fromPrice: 35,
    currency: "EUR",
    priceNote: PRICE_NOTE + " (per vehicle, by zone)",
    groupType: "Private",
    highlights: [
      "Meet & greet in the arrivals hall",
      "Pickup and drop-off anywhere in Mauritius",
      "Fixed, transparent starting prices",
      "Flight-time monitoring",
      "Child seats on request",
    ],
    included: [
      "Private air-conditioned vehicle",
      "Professional driver",
      "Meet & greet with name board",
      "Luggage assistance",
      "Bottled water",
    ],
    excluded: [
      "Gratuities",
      "Extra stops en route (on request)",
      "Overnight surcharge (if applicable)",
    ],
    itinerary: [
      { title: "You send your flight", description: "Share your flight number and hotel when you request the transfer." },
      { title: "We track your arrival", description: "Your driver adjusts to delays automatically." },
      { title: "Meet & greet", description: "Your driver is waiting in arrivals with a name board." },
      { title: "Door to door", description: "Direct, comfortable transfer to your destination." },
    ],
    tags: ["Transfer", "Airport", "Private", "Reliable"],
    mapArea: { label: "SSR International Airport ⇄ your hotel", query: "Sir Seewoosagur Ramgoolam International Airport, Mauritius" },
    hero: { id: "transfer-hero", alt: "Clean air-conditioned transfer vehicle on a Mauritius coastal road", tone: "ocean", orientation: "wide" },
    gallery: [
      { id: "transfer-meet", alt: "Driver holding a name board in an airport arrivals hall", tone: "ocean", orientation: "landscape" },
      { id: "transfer-interior", alt: "Comfortable air-conditioned vehicle interior", tone: "ocean", orientation: "square" },
    ],
    draft: true,
  },
];
